import { PublishedNotes } from "./types";

export function buildEmailHtml(
  notes: PublishedNotes
): string {
  const sectionHtml = notes.detailedNotes
    .map(
      (note) => `
      <div style="margin-bottom: 24px;">
        <h3 style="margin: 0 0 8px 0; font-size: 16px; color: #1a1a1a;">${escapeHtml(note.agendaItemTitle)}</h3>
        <div style="font-size: 14px; color: #444; line-height: 1.6; white-space: pre-wrap;">${escapeHtml(note.content)}</div>
      </div>`
    )
    .join("");

  return `
    <!DOCTYPE html>
    <html>
    <head><meta charset="utf-8"></head>
    <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; color: #333;">
      <h1 style="font-size: 22px; color: #111; margin-bottom: 4px;">Presentation Notes</h1>
      <p style="font-size: 12px; color: #888; margin-top: 0;">Generated by ABNoteTaker</p>

      <div style="background: #f0f4ff; border-radius: 8px; padding: 16px; margin: 20px 0;">
        <h2 style="margin: 0 0 8px 0; font-size: 14px; text-transform: uppercase; color: #666;">Synopsis</h2>
        <p style="margin: 0; font-size: 14px; line-height: 1.5; color: #333;">${escapeHtml(notes.synopsis)}</p>
      </div>

      <h2 style="font-size: 18px; color: #111; border-bottom: 1px solid #eee; padding-bottom: 8px;">Detailed Notes</h2>
      ${sectionHtml}

      <hr style="border: none; border-top: 1px solid #eee; margin: 32px 0 16px 0;">
      <p style="font-size: 11px; color: #aaa; text-align: center;">Sent via ABNoteTaker</p>
    </body>
    </html>
  `;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
